org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError
# JDK do Android Studio (evita Gradle com Java 8 errado). Ajuste o caminho se necessario.
org.gradle.java.home=D\:\\Android Studio\\jbr
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
